language: ruby
rvm:
  - 1.9.3

# env: CUCUMBER_FORMAT=Fivemat

before_install:
  - gem install bundler --pre >> /dev/null 2>&1

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"